
title: Design Patterns Stories
email: info@design-patterns-strories.com
description: > # this means to ignore newlines until "baseurl:"
  Gang Of Four Design Pattern explained as real life stories. 
  Each pattern is implemented in Java and explained in real life story.
##baseurl: /100-words-design-patterns-java # the subpath of your site, e.g. /blog
baseurl: "/patterns" # the subpath of your site, e.g. /blog
my_setting: "/"

url: "https://dstar55.github.io" # the base hostname & protocol for your site
twitter_username: PatternsStories
github_username:  dstar55

permalink: :categories/:title
exclude: [deprecated, vendor, Gemfile, Procfile]
safe: true

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
